apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdemo
  labels:
    app: webappdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webappdemo
  template:
    metadata:
      labels:
        app: webappdemo
    spec:
      containers:
        - name: webappdemo
          image: pnw0080/webappdemo:1.0
          ports:
            - containerPort: 9090
          imagePullPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: webappdemo-service
spec:
  type: NodePort
  selector:
    app: webappdemo
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
